name: Manually pass
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why skip'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello ${{ github.event.inputs.reason }}!"
      - name: Doing nothing
        run: exit 0
